### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#1]
solve the issue using CPP.
provide
codes/algos

**Comment by pawarhrishi21** [comment]
I would like to work on this as a part of Hacktober fest 2020

**Comment by akshitagupta15june** [comment]
Asssigned

PROCESS OF CONTRIBUTION IN THIS REPOSITORY

FORK THIS REPOSITORY
ADD YOUR CODE IN RESPECTIVE FOLDER
CREATE A PULL REQUEST
AFTER A SIMPLE CHECK I WILL MERGE THE PR

HAPPY CODING AND CONTRIBUTING!!!!

**Comment by pawarhrishi21** [comment]
There are two folders related to sorting named 'Sorting&Searching' and 'sorting'.
In which should I add the file?

**Comment by akshitagupta15june** [comment]
sorting one

**Comment by pawarhrishi21** [comment]
I have put up a PR. Please have a look.

**Comment by kritika122000** [comment]
can you please assign me
