### ISSUE TITLE
Create Binary Search

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#104]
Add in searching sorting repo

**Comment by Hardik0307** [comment]
May I work on this @akshitagupta15june ?

**Comment by akshitagupta15june** [comment]
Assigned

PROCESS OF CONTRIBUTION IN THIS REPOSITORY

FORK THIS REPOSITORY
ADD YOUR CODE IN RESPECTIVE FOLDER
CREATE A PULL REQUEST
AFTER A SIMPLE CHECK I WILL MERGE THE PR

HAPPY CODING AND CONTRIBUTING!!!!

**Comment by rebelfire888** [comment]
I would like to work on any searching or sorting algorithms .Pls assign the work to me

**Comment by akshitagupta15june** [comment]
Asssigned

PROCESS OF CONTRIBUTION IN THIS REPOSITORY

FORK THIS REPOSITORY
ADD YOUR CODE IN RESPECTIVE FOLDER
CREATE A PULL REQUEST
AFTER A SIMPLE CHECK I WILL MERGE THE PR

HAPPY CODING AND CONTRIBUTING!!!!
