### ISSUE TITLE
Insert an element at the beginning of linked list and display it.

### ISSUE THREAD

**Issue by gh4abhi** [akshitagit/CPP#114]
Write a program that adds element at the beginning of linked list and displays it.

**Comment by gh4abhi** [comment]
Where can I add the code for this problem?

**Comment by gh4abhi** [comment]
Where can I add code for this problem.

**Comment by akshitagupta15june** [comment]
You can add in linkedlist repo

**Comment by gh4abhi** [comment]
Alright
Thank You
