### ISSUE TITLE
Find Sum-Trees

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#118]
Given a balanced binary tree find sum of all the nodes.
Input Format

First line contains N the number of elements in the tree. Next line contains N space separated elements.
Constraints

0 <= N <= 10^6

-10^7 <= tree.data <= 10^7
Output Format

A single integer : Sum of the tree
Sample Input

3  
1 2 3  

Sample Output

6

**Comment by akshitagupta15june** [comment]
Add in tree repo

**Comment by d2Anubis** [comment]
Can you assign this to me?

**Comment by akshitagupta15june** [comment]
yes assigned to u

**Comment by hritikkhurana10sm** [comment]
Can I work on this as a part of hacktober fest 2020. please assign .

**Comment by akshitagupta15june** [comment]
issue is closed . code is already added please work on differnt issue.
