### ISSUE TITLE
FIND HCF

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#120]
Given N positive numbers, your task is to calculate their HCF.
Input Format

First line of input contains a single integer N, second line contains N space separated positive integers whose HCF is to be computed.
Constraints

N <= 10 and all the numbers lie between 1 and 100.
Output Format

Print HCF of N numbers.
Sample Input

3
2 4 6

Sample Output

2

**Comment by akshitagupta15june** [comment]
ADD IN MATHS FOLDER

**Comment by Harshak50** [comment]
I will work on this

**Comment by pawarhrishi21** [comment]
Please assign this to me as a part of Hactober2020

**Comment by pawarhrishi21** [comment]
You can review my PR #124
