### ISSUE TITLE
Is String a Palindrome?

### ISSUE THREAD

**Issue by pawarhrishi21** [akshitagit/CPP#129]
Write a C++ program to check if a given string of lower case alphabets ('a' to 'z') is a palindrome.

**Comment by pawarhrishi21** [comment]
Add the file to String folder

**Comment by ThePsyk3y** [comment]
Can you assign this to me?

**Comment by shiv-ani-singh** [comment]
Can you please assign this to me?

**Comment by Maitryee-Choudhary** [comment]
Can I work on this?

**Comment by kratikaatgithub** [comment]
Hi @pawarhrishi21  can you also assign this issue to me? I would like to work on this as part of hacktoberfest 2020.
Thanks

**Comment by hritikkhurana10sm** [comment]
Can I work on this as a part of hacktober fest 2020. please assign .

**Comment by kothawade29** [comment]
Hello @pawarhrishi21  can you please assign this issue ?
