### ISSUE TITLE
DECIMAL TO OCTAL

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#131]
Take N (number in decimal format). Write a function that converts it to octal format. Print the value returned.
Input Format

Constraints

0 < N <= 1000000000
Output Format

Sample Input

63

Sample Output

77

**Comment by akshitagupta15june** [comment]
Add in maths folder

**Comment by ThePsyk3y** [comment]
Can I take this?

**Comment by akshitagupta15june** [comment]
yes i am assigning to u

**Comment by akshitagupta15june** [comment]
PROCESS OF CONTRIBUTION IN THIS REPOSITORY

FORK THIS REPOSITORY
ADD YOUR CODE IN RESPECTIVE FOLDER
CREATE A PULL REQUEST
AFTER A SIMPLE CHECK I WILL MERGE THE PR

HAPPY CODING AND CONTRIBUTING!!!!

**Comment by sagarr70** [comment]
Can I work on it as a part of hacktoberfest 2020.

**Comment by vaibhavsahu342** [comment]
can i take this?

**Comment by akshitagupta15june** [comment]
i have assigned it
