### ISSUE TITLE
IS PARENTHESIS BALANCED?

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#134]
You are given a string of brackets i.e. '{', '}' , '(' , ')', '[' , ']' . You have to check whether the sequence of parenthesis is balanced or not.
For example, "(())", "(())()" are balanced and "())(", "(()))" are not.
Input Format

A string of '(' , ')' , '{' , '}' and '[' , ']' .
Constraints

1<=|S|<=10^5
Output Format

Print "Yes" if the brackets are balanced and "No" if not balanced.
Sample Input

(())

Sample Output

Yes

**Comment by akshitagupta15june** [comment]
ADD IN THE SUITABLE CODE REPO

**Comment by iFrogHop2Worlds** [comment]
I'm assuming I should wait till October for making requests but it seems a few people begun. If we submit now will it be valid for hacktober?
