### ISSUE TITLE
Largest Number by Rearranging array

### ISSUE THREAD

**Issue by pawarhrishi21** [akshitagit/CPP#140]
Given an array of non-negative integers, arrange them such that they form the largest number. Write a C++ program to output the largest number possible.

Add file to Interview Questions folder.

**Comment by Pratik-ahirrao** [comment]
I would like to work on this.
Please assign it to me.
Thankyou

**Comment by Pratik-ahirrao** [comment]
Please assign it to me so that i can work on this issue.

**Comment by kratikaatgithub** [comment]
Hi @akshitagupta15june can you also assign this issue to me? I would like to work on this as part of hacktoberfest 2020.
Thanks

**Comment by Pratik-ahirrao** [comment]
I am already working on this issue

**Comment by pawarhrishi21** [comment]
@Pratik-ahirrao Go on. Make a Pull Request and link it here

**Comment by pranshi112** [comment]
Can I work on this?
