### ISSUE TITLE
Kth smallest element in a Binary Search Tree

### ISSUE THREAD

**Issue by pawarhrishi21** [akshitagit/CPP#142]
Given a binary search tree, write a function to find the kth smallest element in the tree. Implement the C++ program.

Add file to trees folder.

**Comment by SourabhBadhya** [comment]
Can I take this issue?

**Comment by Maitryee-Choudhary** [comment]
Can I work on this project?

**Comment by hritikkhurana10sm** [comment]
Can I work on this as a part of hacktober fest 2020. please assign .

**Comment by pawarhrishi21** [comment]
@SourabhBadhya. Put up a PR and link it in this issue

**Comment by SourabhBadhya** [comment]
Ok assign it to me. I will do it.

**Comment by Ajit-53** [comment]
i will do it in very optimize way. plz asign me for this task

**Comment by kritika122000** [comment]
can you please assign me

**Comment by SourabhBadhya** [comment]
#421 The pull request has been submitted here for Kth smallest element in Binary Search Tree
