### ISSUE TITLE
PATTERN TRIANGLE

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#155]
Take N (number of rows), print the following pattern (for N = 4).

                       1 
                     2 3 2
                   3 4 5 4 3
                 4 5 6 7 6 5 4

Input Format

Constraints

0 < N < 10

**Comment by akshitagupta15june** [comment]
ADD IN PATTERNS FOLDER

**Comment by aswarth123** [comment]
I would like to solve can you assign it to me?

**Comment by Maitryee-Choudhary** [comment]
Can you assign to me?

**Comment by akshitagupta15june** [comment]
Ok
