### ISSUE TITLE
Print the Fibonacci series for n=20

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#160]

**Comment by akshitagupta15june** [comment]
Add in daily code repo

**Comment by dolonmandal** [comment]
Can I  work on this as a part of hacktober fest 2020.  please assign .

**Comment by akshitagupta15june** [comment]
Yes Ofcourse

**Comment by Mayankjha997** [comment]
Hey, can I work on this as apart of hactober fest 2020 please

**Comment by kratikaatgithub** [comment]
Hi @akshitagupta15june can you also assign this issue to me? I would like to work on this as part of hacktoberfest 2020.
Thanks

**Comment by hritikkhurana10sm** [comment]
Can I work on this as a part of hacktoberfest 2020. please .

**Comment by akshitagupta15june** [comment]
issue is closed . code is already added please work on different issue.
