### ISSUE TITLE
MATRIX SEARCH

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#172]
STAR THIS REPO!

Given an n x m matrix, where every row and column is sorted in increasing order, and a number x . Find if element x is present in the matrix or not.

Input Format

First line consists of two space separated integers N and M, denoting the number of element in a row and column respectively. Second line of each test case consists of N*M space separated integers denoting the elements in the matrix in row major order. Third line of each test case contains a single integer x, the element to be searched.
Constraints

1 <= N,M <= 30 0 <= A[i] <= 100000

Output Format

Print 1 if the element is present in the matrix, else 0.

Sample Input

3 3
3 30 38
44 52 54
57 60 69

62

Sample Output

0

**Comment by ayush523** [comment]
I would like to work on this issue.

**Comment by Maitryee-Choudhary** [comment]
I would like to work on this.Can you assign me?

**Comment by muskan-goel09** [comment]
I would like to work on it.

**Comment by hritikkhurana10sm** [comment]
I would like to work on this as for hacktober fest 2020. please assign

**Comment by sagarr70** [comment]
I would like to Work on it. Please assign.
