### ISSUE TITLE
Add code for Largest Sum Contiguous Subarray

### ISSUE THREAD

**Issue by yashasvimisra2798** [akshitagit/CPP#180]
Write an efficient program to find the sum of contiguous subarray within a one-dimensional array 
of numbers which has the largest sum.

**Comment by yashasvimisra2798** [comment]
I want to work on this issue for hacktoberfest. Please assign this to me.

**Comment by akshitagupta15june** [comment]
Ok

**Comment by sakibmahmud** [comment]
Hi, 
I would like to contribute to this issue.

**Comment by akshitagupta15june** [comment]
ok

**Comment by yashasvimisra2798** [comment]
I'll be contributing in C++ language 
@sakibmahmud @akshitagupta15june
