### ISSUE TITLE
Rotate an array to the left by 3 position.

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#186]
add in array folder.
Rotate an array to the left by 3 position.
n<=10

**Comment by gokulkannan7** [comment]
@akshitagupta15june can I tackle the issue?

**Comment by akshitagupta15june** [comment]
yeah

**Comment by akshitagupta15june** [comment]
assigned

**Comment by gokulkannan7** [comment]
@akshitagupta15june since this is a part of hacktoberfest, can I open PR in the first week of October?

**Comment by Harshal0902** [comment]
@akshitagupta15june can I work on this issue?

**Comment by gokulkannan7** [comment]
@akshitagupta15june I have opened a PR, pls check
