### ISSUE TITLE
Rotate an array to the right by 3 position.

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#187]
add in array folder.
Rotate an array to the right by 3 position.
n<=10

**Comment by Praddyumn16** [comment]
Please assign this issue to me, i would like to work on it @akshitagupta15june

**Comment by akshitagupta15june** [comment]
ok

**Comment by Praddyumn16** [comment]
Can it be done in cpp?

**Comment by Harshal0902** [comment]
@akshitagupta15june can I work on this issue?

**Comment by mallick370** [comment]
Please assign this issue to me, i would like to work on it @akshitagupta15june
