### ISSUE TITLE
Coin Change problem in DP

### ISSUE THREAD

**Issue by ArvindR07** [akshitagit/CPP#191]
### - I would like to contribute the **Coin Change** problem under Dynamic Programming.

**Problem Statement:**
 Given a set of coins and a target value, find the number of distinct ordered ways to make that sum assuming you have infinite supply of the given coins.

**Comment by piyush9311** [comment]
May I work on this issue please

**Comment by ArvindR07** [comment]
Maybe you can create another issue for different variant of this problem ie. all possible ways and contribute in that. What do you say?

**Comment by piyush9311** [comment]
sir you mean to say problem related to dynamic programming?

**Comment by piyush9311** [comment]
> Maybe you can create another issue for different variant of this problem ie. all possible ways and contribute in that. What do you say?

Sir will making an issue count to my PR , because I want to make PR's for HACKTOBERFEST?

**Comment by ArvindR07** [comment]
The problem statement can be modified as all possible ways instead of distinct ordered ways. You can work on that. Just create a new issue on the issues page and contribute in that.

**Comment by ArvindR07** [comment]
No problem. Just create a new issue for that another problem. I am also a Hacktoberfest participant. It will still be assigned to you if mentor sees.

**Comment by piyush9311** [comment]
Ohk sir thanks a lot.

**Comment by ArvindR07** [comment]
I am ready to contribute to this problem. @akshitagupta15june

**Comment by akshitagupta15june** [comment]
Ok assigning you.
