### ISSUE TITLE
Palindromic Integer

### ISSUE THREAD

**Issue by pawarhrishi21** [akshitagit/CPP#192]
Determine whether a non-negative integer is a palindrome without using extra space.

Add in the Daily code folder.

**Comment by piyush9311** [comment]
May I work on this issue pls as it will help me alot to boost my open source contribution and also for hacktoberfest

**Comment by akshitagupta15june** [comment]
Sure!
Thanks for the issues @pawarhrishi21

**Comment by DevanshD3** [comment]
Hey can I work on this issue for the Hactoberfest 2020. It will help me get a start open source contribution

**Comment by piyush9311** [comment]
Sorry its already assigned to me and I am working on it .You can work on other issues.

**Comment by pawarhrishi21** [comment]
> Sure!
> Thanks for the issues @pawarhrishi21

Sure! You're welcome
