### ISSUE TITLE
Remove duplicates from a singly linked list

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#196]
add in linkedlist folder

**Comment by JINDAL-JJ** [comment]
Please assign me over this issue. I would like to contribute over this under hactoberfest. Thank You!

**Comment by meenal2000** [comment]
hey akshita! 
I have never made an open source contribution and I wanted this to be my first contribution . can you please assign me this issue?

**Comment by dipanshug124** [comment]
Please assign this issue to me

**Comment by chhipanikhil9** [comment]
I can write code in cpp.

**Comment by Durveshpal** [comment]
Hey, I can do because I have an abstract data type of a singly linked list, and my compiler is stuck when running this part of the test code.

    test.removeDuplicates();
    System.out.println("removeDuplicates() has been run, check following output for counts of 3");
    test.print();

**Comment by wasimparsani** [comment]
Please assign me this task I can definitely do it

**Comment by Rahulraj31** [comment]
Please assign me this task
