### ISSUE TITLE
Multiply Large Numbers

### ISSUE THREAD

**Issue by AC-BOSS** [akshitagit/CPP#215]
I would like to add the code for multiplication of large numbers(which may or may not contain decimals) in the dailycode folder

**Comment by mk-singhal** [comment]
Hi @akshitagupta15june ,
I would like to work on this...

**Comment by satwik-chowdary** [comment]
I can work on this

**Comment by Rituraj-commits** [comment]
I would like to work on this  issue.

**Comment by Ajeet1606** [comment]
Hey @AC-BOSS I want to work as a part of hactoberfest 2020.
Please guide a bit how should I proceed.

**Comment by AC-BOSS** [comment]
@Ajeet1606 I am also a contributer, and I was asking to work on this. And contributions to this repository won't count in progress in Hacktoberfest anymore.
