### ISSUE TITLE
0-1Knapsack

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#29]
You are packing for a vacation on the sea side and you are going to carry only one bag with capacity S (1 <= S <= 1000). You also have N (1<= N <= 1000) items that you might want to take with you to the sea side. Unfortunately you can not fit all of them in the knapsack so you will have to choose. For each item you are given its size and its value. You want to maximize the total value of all the items you are going to bring. What is this maximum total value?
Input Format

On the first line you are given N and S.
Second line contains N space separated integer where ith integer denotes the size of ith item. Third line contains N space seperated integers where ith integer denotes the value of ith item.
Constraints

1 <= S,N <= 1000
Output Format

Output a single integer showing the maximum value that can be obtained by optimally choosing the items.
Sample Input

5 4
1 2 3 2 2 
8 4 0 5 3

Sample Output

13

Explanation

Total capacity = 4.
Pick size 1 with value 8 and size 2 with value 5.

**Comment by akshitagupta15june** [comment]
Add in interview question repo of cpp.

**Comment by shibrahmachari** [comment]
Can I add to this

**Comment by sindhujaponnuru** [comment]
Great issue. I will be working on this.

**Comment by iaish-max** [comment]
I am a beginner in open source contribution , can i work on this.

**Comment by akshitagupta15june** [comment]
yeah!!
