### ISSUE TITLE
Create Pascal pattern

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#30]
Given an integer N, print Pascal Triangle upto N rows.
Input Format

Single integer N.
Constraints

N <= 10
Output Format

Print pascal triangle.
Sample Input

4

Sample Output

           1
         1   1
       1   2   1
     1   3   3   1

**Comment by akshitagupta15june** [comment]
Add in patterns repo of CPP

**Comment by jabbar86** [comment]
@akshitagupta15june  i would like to take this.

**Comment by ARYAMANSHIVAMJHA** [comment]
i have already written the code for the same

**Comment by akshitagupta15june** [comment]
Yup add the code in patterns
