### ISSUE TITLE
Moorey's Voting algorithm

### ISSUE THREAD

**Issue by YUVRAJMOTWANI99** [akshitagit/CPP#321]
Find majority element (>n/2) in an array.
INPUT:- [3,3,1,1,1,3,3]
OUTPUT:- 3.

**Comment by YUVRAJMOTWANI99** [comment]
@akshitagit pls. assign this to me.

**Comment by chauhannaman98** [comment]
@akshitagit I have already complete this one in #351

**Comment by YUVRAJMOTWANI99** [comment]
@chauhannaman98  sorry I did not see.
