### ISSUE TITLE
This repo is marked as Invalid in Hacktober fest

### ISSUE THREAD

**Issue by singhalpranav22** [akshitagit/CPP#370]

**Comment by akshitagupta15june** [comment]
who told you?

**Comment by akshitagupta15june** [comment]
hacktoberfest has not said this.

**Comment by singhalpranav22** [comment]
My pull request in website is invalid.
<img width="524" alt="Screenshot 2020-10-01 at 12 53 57 AM" src="https://user-images.githubusercontent.com/51447798/94730380-c2925800-0380-11eb-83ec-aca7fb7a591b.png">
<img width="724" alt="Screenshot 2020-10-01 at 12 55 02 AM" src="https://user-images.githubusercontent.com/51447798/94730386-c4f4b200-0380-11eb-804f-b7c1ac4976c6.png">

**Comment by akshitagupta15june** [comment]
i dont know why is this happening! hacktoberfest have not raised a issue here.

**Comment by singhalpranav22** [comment]
yes you are right

**Comment by singhalpranav22** [comment]
Similar issue with python repo as well . Please check.

**Comment by akshitagupta15june** [comment]
Many people just for there fun have reported spam.

**Comment by singhalpranav22** [comment]
Unfortunate
