### ISSUE TITLE
Just a thought

### ISSUE THREAD

**Issue by SarbojitAMD** [akshitagit/CPP#587]
To maintainer(@akshitagupta15june) and other contributors,

Great initiative and good to see many are proactively contributing yet sources are arranged so nicely 👍. Since the community is growing very fast I felt it is good to share some points which might be helpful for everyone.

1. We often think about the number of PRs submitted/accepted by individual matters but trust me code review is equally important. If you can find a bug in other's code or suggest some improvements that are even better. It prepares you to understand other's code which is not an easy task. In industry, you have to spent lot of time debugging and fixing codes written by others hence start reviewing other's code.

2. Coding is not JUST GETTING correct results it is much more than that. In the beginning, one must be in hurry to fix the problem but an experienced developer or good interviewer would look into how are you solving the problem (sometimes people look for the approach). Often code written in CPP data members are all public which is the last thing one should do because this shows you are not thinking about data protection, other things could be not having sufficient comments in the code, bad naming. Try to develop this habit from the beginning will help a lot in the future.

3. It is my personal opinion why do you need to create an issue for adding some code. You can always push your PR and let the maintainer decide if it is worth adding or not.

**Comment by akshitagupta15june** [comment]
Thanks for sharing @SarbojitAMD

**Comment by SarbojitAMD** [comment]
In case anyone solving Problems related to Tree, Linked list, Doubly Linked List, Stack, or Queue general habit is to create a Tree DS for their own program what if Tree DS is already available, one just needs to use it in the program he/she is trying to solve. I have added a header-only DS file that can be used in any CPP program. Feel free to use  https://github.com/SarbojitAMD/Header_Only_DS 

All suggestions/improvements are welcome.
