### ISSUE TITLE
Inorder traversal in CPP

### ISSUE THREAD

**Issue by milanj-1** [akshitagit/CPP#70]

**Comment by milanj-1** [comment]
Made a new PR @akshitagupta15june, please check

**Comment by milanj-1** [comment]
Could you please link the pull request here @akshitagupta15june

**Comment by pawarhrishi21** [comment]
I would like to work on this as a part of Hacktober fest

**Comment by dolonmandal** [comment]
I would like to work on this as a part of hacktober fest 2020. Can you please assign.

**Comment by akshitagupta15june** [comment]
Assigned

**Comment by hritikkhurana10sm** [comment]
Can I work on this as a part of hacktober fest 2020. please assign .

**Comment by akshitagupta15june** [comment]
issue is closed . code is already added please work on differnt issue.
