### ISSUE TITLE
Strings-Remove Duplicates

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#86]
Take as input S, a string. Write a function that removes all consecutive duplicates. Print the value returned.
Input Format

String
Constraints

A string of length between 1 to 1000
Output Format

String
Sample Input

aabccba

Sample Output

abcba

Explanation

For the given example, "aabccba", Consecutive Occurrence of a is 2, b is 1, and c is 2.

After removing all of the consecutive occurences, the Final ans will be : - "abcba".

**Comment by akshitagupta15june** [comment]
Add in strings repo of CPP

**Comment by rishi-1092** [comment]
can i contribute?

**Comment by akshitagupta15june** [comment]
open for all

**Comment by heyyviv** [comment]
can i work on it

**Comment by akshitagupta15june** [comment]
PROCESS OF CONTRIBUTION IN THIS REPOSITORY

FORK THIS REPOSITORY
ADD YOUR CODE IN RESPECTIVE FOLDER
CREATE A PULL REQUEST
AFTER A SIMPLE CHECK I WILL MERGE THE PR

HAPPY CODING AND CONTRIBUTING!!!!

**Comment by rishi-1092** [comment]
Hello @akshitagupta15june , I have made a pr for the issue, if you can check the same and merge my pr such that it counts for Hacktoberfest , it would be great

**Comment by chehak123** [comment]
Can i contribute ?
