### ISSUE TITLE
Check whether two strings are anagram of each other

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#89]
Check whether two strings are anagram of each other
add in strings folder

**Comment by AltCtrlDel1999** [comment]
I would like to work on this issue

**Comment by akshitagupta15june** [comment]
PROCESS OF CONTRIBUTION IN THE REPOSITORIES

FORK THE REPOSITORY OF YOUR CHOICE
ADD YOUR CODE IN RESPECTIVE FOLDER
CREATE A PULL REQUEST
AFTER A SIMPLE CHECK I WILL MERGE THE PR

HAPPY CODING AND CONTRIBUTING!!!!

**Comment by Code-Recursion** [comment]
i would liek to work on this issue, kindly assign it to me.

**Comment by chehak123** [comment]
I would like to work on it.
