### ISSUE TITLE
String Compression

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/CPP#92]
Take as input S, a string. Write a function that does basic string compression. Print the value returned. E.g. for input “aaabbccds” print out a3b2c2d1s1.
Input Format

A single String S
Constraints

1 < = length of String < = 1000
Output Format

The compressed String.
Sample Input

aaabbccds

Sample Output

a3b2c2d1s1

Explanation

In the given sample test case 'a' is repeated 3 times consecutively, 'b' is repeated twice, 'c' is repeated twice and 'd and 's' occurred only once.

**Comment by akshitagupta15june** [comment]
add in strings folder

**Comment by rishi-1092** [comment]
can i work on this if its okay?

**Comment by akshitagupta15june** [comment]
PROCESS OF CONTRIBUTION IN THIS REPOSITORY

FORK THIS REPOSITORY
ADD YOUR CODE IN RESPECTIVE FOLDER
CREATE A PULL REQUEST
AFTER A SIMPLE CHECK I WILL MERGE THE PR

HAPPY CODING AND CONTRIBUTING!!!!

**Comment by rasacharjee** [comment]
Hello @akshitagupta15june  can you please assign the issue to me

**Comment by akshitagupta15june** [comment]
PROCESS OF CONTRIBUTION IN THIS REPOSITORY

FORK THIS REPOSITORY
ADD YOUR CODE IN RESPECTIVE FOLDER
CREATE A PULL REQUEST
AFTER A SIMPLE CHECK I WILL MERGE THE PR

HAPPY CODING AND CONTRIBUTING!!!!

**Comment by rasacharjee** [comment]
Hello @akshitagupta15june , I have made a pr for the issue, can you please look into the same and merge my pr such that it counts for Hacktoberfest too.

**Comment by chehak123** [comment]
Can I work on this issue?

**Comment by AC-BOSS** [comment]
May I work on this?
